# Generated by Django 4.0.4 on 2022-05-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxid', models.CharField(max_length=255)),
                ('wxname', models.CharField(max_length=50)),
                ('identify', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
